### ISSUE TITLE
As a customer i want to see current car repair status

### ISSUE THREAD

**Issue by Marii2806** [4GeeksAcademy/pimp-my-ride-mia61#4]

**Comment by Marii2806** [comment]
- [ ] I can quick search current car repair status without signing in.

- [ ] I can sign up to see current car repair status. I can login to my account when i forgot my password..

- [ ] I cannot modify my car repair status.

- [ ] I want to know an estimate date of completion.

- [ ] I want to receive text message when car is ready for pick up.

**Comment by Michaelmira** [comment]
- [ ]  I want to recieve Email's and textmessages with link to status when there is an update

**Comment by Marii2806** [comment]
- Work Order page that includes progressbar and WO details. READ ONLY
