### ISSUE TITLE
As a customer i need a car repair so i need a website that i can contact a repair shop

### ISSUE THREAD

**Issue by Michaelmira** [4GeeksAcademy/pimp-my-ride-mia61#6]

**Comment by Michaelmira** [comment]
Acceptance Criteria 

- [ ]  I need a website with a phone number.
- [ ]  I need a website with a email.
- [ ]  I need a website with an address. 
- [ ]  I need an estimate!

**Comment by Marii2806** [comment]
- [ ] i want to contact business owner to get an estimate by inputting my personal information and reason why I'm contacting
