### ISSUE TITLE
As a customer, i want to see my order history.

### ISSUE THREAD

**Issue by Michaelmira** [4GeeksAcademy/pimp-my-ride-mia61#7]

**Comment by Michaelmira** [comment]
Acceptance criteria:

- [ ] I need a page all my previous transactions and invoices.
- [ ] I need this history page to organized be per vehicle make and model.

**Comment by Marii2806** [comment]
customer dashboard page that includes:

> list of all work orders (read only), customer should be able to click on particular order which will lead him to Work Order Page

> personal information (should be linked to Customer Profile Page)
